language: python
python:
  - "3.5"
before_install:
  - mv .travis.secrets.yaml secrets.yaml
  - mkdir ./ssl
  - touch ./ssl/fullchain.pem
  - touch ./ssl/privkey.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
