language: python
python:
  - "3.5"
before_install:
  - mv .travis.secrets.yaml secrets.yaml
  - touch fake_key.pem
  - touch fake_key.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
