branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
language: python
python:
- '3.5'
before_install:
- mv .travis.secrets.yaml secrets.yaml
- touch fake_key.pem
- touch fake_key.pem
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- echo -n $GIT_TAG > public/version
- git commit -m "Set build VERSION number" public/version
- git tag $GIT_TAG -a -m "Generated tag from Travis CI build $TRAVIS_BUILD_NUMBER"
- git push --quiet https://$GH_TOKEN@github.com/pascalwilbrink/home-assistant-config
  $GIT_TAG
env:
  global:
  - secure: USJLqU6FO4h6oOAVgtxqeA/zLzeAsidETOQIBZYTcZ6eOXyaUh6VJZmJLgK8E8dkyWAthRZRwWNsH0WMCWXHknpE+eVWa3sACfRX3shRvaGJq82NXWRLC3yditfqKvIWZtvVx3lo3gAzN/iWG9PvTSk4IsFQMSLH8hJnbDokhmmknBung/61BS+nrPR3XYLU3Fl6CbFQWRHVw5mw+2VuDxDgoizgYOyW222S0p2+xEMICJ05iJM9v+BOqUhUTE9j3BzZ9misLZjb2j3Rqxj1FNTkwRmDNqbACGyi/iUBX2j09nTmE9wj3kWMPfnu0u/JI1yRG9j7Q6xU4ILT61hmOIbg6d0P3JFVqJ4KY6+TGsbe/UFBCU6b2B7L24DCLE12a/srn2Oe2eIcQIJ4L4kxxGdZogDwCBdygDc/qIvOpy2thn9xpOPittuA/ancputfR/NYE0rpIClYz0amTofICiSm1s23iimyj3CsNPKX62GoVz3ErHCDDXDpnW35Mrkg9qOwWXTS7okghh5YadJkAbFX9de843COkbMYDvUxmEAHOT6ndWAHPajwNMr5X2DQlGWlxFboZouMFPH2WLTY83SHIwCQfOgZvxPrFdBLm1y7eF5bgDPEq1SdTn7SHSpC2Op60LezzVCeURdzwqr+iBYIr9+jvP1IxqVyWZVHyl0=
  - secure: tZ1zWAsJIEYkugYQ7IzB61avGinTG+2pYQ5LaKhJpO4LeAAKFXOlygfl4NGF7kWlgEerZ6kVU91S/G7AkybDsz8WaiDdNqJvdjzm4gUJEcOMl7KuA5EpK8dfGHRyCoPi0/oKJfXyje8gkSRpXKFcPz2ukOoPUN/ug5XJ1/VZueIYQbm5MueERbQrQytNFqTp/K88HTxbHaY6ECoQHEbzio6gQHSHbL8yzbs03jlP+oVvG1LP/BE+U6GjScYgRemEqHqJChObyApxGpP4PjsTRanum8+H89AagGaOErC14aNs+m47UZoqkp3xrFapK4DJEdQrKgENnVl55tDBFF1kt1D8lh3DMpLR6zbLeSPnn7WtQAdrowDkFnf3dklHSL3u3TiHAdckzDgfN+wmSmS5Ir0gY0GHjmO6F3tGP0+K29u38Ea62+MSpRyE27ODpKZCLzOUHHDjV7iD+df7HWzgm6PiJfBhPNladlxu+0WoN5+tb3P9nr2JCug7xSgNvljwS09RQ5XDlrL76mVmFNSBTfkzN1E/yX+0g6VGOvwxtej6ULheT8Ca6Etik0hFacmL0bZTlSOC3LMOi05CX9SW5g1UDOU/m02EJSq0vh8UJntcGXQCwOAOlhiGex8FFwckhHvfKYspPP5fqKQwvtLT2tDoRL1UIN7nFempg51DDVs=
