# General
homeassistant:
  latitude: !secret lat
  longitude: !secret lng
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_networks
    - type: homeassistant

  customize: !include customizations.yaml

# Hue
hue:
  bridges:
    - host: !secret hue_bridge
      allow_unreachable: true
      allow_hue_groups: true

# Telegram
telegram_bot:
    - platform: polling
      api_key: !secret telegram_api
      allowed_chat_ids:
        - !secret telegram_chat_id

# Google
google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

# Media players
media_player:

    # TV
    - platform: philips_android_tv
      name: TV
      host: !secret philips_tv_host
      mac: !secret philips_tv_mac
      username: !secret philips_tv_username
      password: !secret philips_tv_password

    # Spotify
    - platform: spotify
      client_id: !secret spotify_client
      client_secret: !secret spotify_secret

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key

# UI
lovelace:
    mode: yaml

# API
http:
    trusted_networks:
      - !secret trusted_networks
    server_port: !secret port
    base_url: !secret duckdns_url
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key

# MQTT
mqtt:
    broker: !secret hassio_ip
    port: !secret hassio_mqtt_port

# Discovery
discovery:

# Default config
default_config:

# Text to speech
tts:
  - platform: google_translate

# Groups
group: !include groups.yaml

# Automations
automation: !include automations.yaml

# Scripts
script: !include scripts.yaml

# Zones
zone: !include zones.yaml

# Sensors
sensor: !include sensors.yaml
