# General
homeassistant:
  latitude: !secret lat
  longitude: !secret lng
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_networks
    - type: homeassistant

  customize: !include customizations.yaml

# Hue
hue:
 bridges:
   - host: !secret hue_bridge
     allow_unreachable: true
     allow_hue_groups: true

# Telegram
#telegram_bot:
 #   - platform: polling
  #    api_key: !secret telegram_api
   #   allowed_chat_ids:
    #    - !secret telegram_chat_id

# Google
google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

# Media players
media_player:

    # Spotify
   - platform: spotify
     client_id: !secret spotify_client
     client_secret: !secret spotify_secret
    # Plex
   - platform: plex

# Owntracks
owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: false
  
# Device tracker
device_tracker:
  - platform: mqtt
    devices:
      pascal_htcu12:
        'owntracks/htcu12/u1'

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key

# Shopping list
shopping_list:

# UI
lovelace:
    mode: yaml

# Frontend
frontend:
  themes: !include themes.yaml

# API
http:
    trusted_networks:
      - !secret trusted_networks
    server_port: !secret port
    base_url: !secret duckdns_url
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key

#MQTT
mqtt:
   broker: !secret hassio_ip
   port: !secret hassio_mqtt_port
   username: !secret mqtt_username
   password: !secret mqtt_password

# Discovery
discovery:

# Default config
default_config:

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

# Groups
group: !include groups.yaml

# Automations
automation: !include automations.yaml

# Scripts
script: !include scripts.yaml

# Zones
zone: !include zones.yaml

# Sensors
sensor: !include sensors.yaml

# Binary sensors
binary_sensor: !include binary_sensors.yaml
