resources:
    - url: /local/cards/test-card.js
      type: module
    - url: /local/cards/spotify-card.js
      type: module
    - url: /local/cards/mini-media-player-bundle.js
      type: module
    - url: /local/cards/calendar-card.js
      type: module

title: Home
views:
  - !include views/01_dashboard.yaml
  - !include views/02_livingroom.yaml
  - !include views/03_bedroom.yaml
  - !include views/04_bathroom.yaml
  - !include views/05_kitchen.yaml
