title: Home
views:
  - title: Dashboard
    icon: mdi:view-dashboard
    cards:
      - card:
          title: Agenda
          type: entities
          entities:
            - entity: calendar.pascal_wilbrink_gmail_com
  - title: Livingroom
    icon: mdi:sofa
  - title: Bedroom
    icon: mdi:hotel
  - title: Bathroom
    icon: mdi:shower-head
  - title: Kitchen
    icon: mdi:fridge-outline